import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NavigationMenu from "@/shared/NavigationMenu";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={"antialiased dark bg-background text-foreground"}>
				<NextUIProvider className="min-h-screen">
					<AuthProvider>
						<NavigationMenu />
						<main className="px-5 pb-5">{children}</main>
					</AuthProvider>
				</NextUIProvider>
			</body>
		</html>
	);
}
