import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import Sidebar from "@/shared/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<AuthProvider>
					<Sidebar />
					<main className="container mx-auto px-10">{children}</main>
					<Toaster />
				</AuthProvider>
			</body>
		</html>
	);
}
